version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1234:80"
    volumes:
      - ./app:/var/www/html

  database:
    image: mariadb
    restart: always
    volumes:
        - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: ''

volumes:
  db_data: